<?php if (!defined('FARI')) die(); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Language" content="en" />

	<meta name="description" content="Fari Framework" />

	<title>Fari Framework</title>

    <?php stylesheetLinkTag('akrabat'); ?>
</head>

<body>
	<div id="content">
		<?php foreach (flash() as $message): ?>
			<div class="flash <?php echo $message['key'] ;?>"><?php echo $message['text']; ?></div>
		<?php endforeach ;?>

		<?php echo $template; ?>
	</div>
</body>
</html>