<?php if (!defined('FARI')) die(); ?>
<h1>Add an album</h1>

<form action="<?php url('/albums/add/'); ?>" method="post">
    <table>
        <tr class="required">
            <th><label class="required">Artist:</label></th>
            <td><input type="text" class="text" name="artist" /></td>
        </tr>
        <tr class="required">
            <th><label class="required">Title:</label></th>
            <td><input type="text" class="text" name="title" /></td>
        </tr>
        <tr>
            <th>&nbsp;</th>
            <td><input type="submit" class="button" name="login" value="Add" /></td>
        </tr>
    </table>
</form>