<?php if (!defined('FARI')) die(); ?>
<h1>Edit an album</h1>

<form action="<?php url('/albums/edit/' . $album['id']); ?>" method="post">
    <table>
        <tr class="required">
            <th><label class="required">Artist:</label></th>
            <td><input type="text" class="text" name="artist" value="<?php echo $album['artist']; ?>" /></td>
        </tr>
        <tr class="required">
            <th><label class="required">Title:</label></th>
            <td><input type="text" class="text" name="title" value="<?php echo $album['title']; ?>" /></td>
        </tr>
        <tr>
            <th>&nbsp;</th>
            <td><input type="submit" class="button" name="login" value="Edit" /></td>
        </tr>
    </table>
</form>