CREATE TABLE [albums] ([id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, [artist] VARCHAR(100) NOT NULL, [title] VARCHAR(100) NOT NULL);
INSERT INTO albums VALUES(1007,'Fugee','Fu-Gee-La');
INSERT INTO albums VALUES(1008,'De La Soul','Kicked Out the House');
INSERT INTO albums VALUES(1009,'Reel Big Fish','I&#039;ll Never Be');
INSERT INTO albums VALUES(1010,'Cast','Alright');
INSERT INTO albums VALUES(1011,'a-ha','I Call Your Name');
INSERT INTO albums VALUES(1012,'Sheryl Crow','Leaving Las Vegas');
INSERT INTO albums VALUES(1013,'Republica','Ready to Go');
INSERT INTO albums VALUES(1014,'Nick Cave and the Bad Seeds','Where the Wild Roses Grow');
INSERT INTO albums VALUES(1015,'Red Hot Chili Peppers','One Hot Minute');
INSERT INTO albums VALUES(1016,'Marcy Playground','Ancient Walls of Flowers');
INSERT INTO albums VALUES(1017,'Garbage','Dumb');
INSERT INTO albums VALUES(1018,'Stakka Bo','Here We Go');
INSERT INTO albums VALUES(1019,'Eels','Susan&#39;s House');
INSERT INTO albums VALUES(1020,'Stone Temple Pilots','Big Bang Baby');
INSERT INTO albums VALUES(1021,'Michael Jackson','You Are Not Alone');
INSERT INTO albums VALUES(1022,'Soundgarden','Never the Machine Forever');
CREATE TABLE [users] ([id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, [username] VARCHAR(30), [password] VARCHAR(30), [realname] VARCHAR(50));
INSERT INTO users VALUES(1,'admin','d033e22ae348aeb5660fc2140aec35850c4da997','Radek Stepan');
