<?php if (!defined('FARI')) die(); ?>
<h1>Login</h1>

<form action="<?php url('login'); ?>" method="post">
    <table>
        <tr class="required">
            <th><label class="required">Username:</label></th>
            <td><input type="text" class="text" name="username" /></td>
        </tr>
        <tr class="required">
            <th><label class="required">Password:</label></th>
            <td><input type="password" class="text" name="password" /></td>
        </tr>
        <tr>
            <th>&nbsp;</th>
            <td><input type="submit" class="button" name="login" value="Login" /></td>
        </tr>
    </table>
    <input type="hidden" name="token" value="<?php echo $token; ?>">
</form>